### ISSUE TITLE
problem while reading bookmark from safari

### ISSUE THREAD

**Issue by alexisparis** [CCharlieLi/Bookmark#1]
Hello,

It seems we have something special with bookmarks from safari.
When I try readFromHTMLFile on such file, I get :

Error: There are errors in your xml file: not well-formed (invalid token)
    at Object.module.exports [as toJson] (/Users/para042/linkguardian/html2links/node_modules/xml2json/lib/xml2json.js:172:15)
    at eachLine (/Users/para042/linkguardian/html2links/node_modules/bookmark-parser/lib/bookmark_parser/html_parser.js:50:39)
    at /Users/para042/linkguardian/html2links/node_modules/line-reader/lib/line_reader.js:279:15
    at getLine (/Users/para042/linkguardian/html2links/node_modules/line-reader/lib/line_reader.js:166:7)
    at Object.nextLine (/Users/para042/linkguardian/html2links/node_modules/line-reader/lib/line_reader.js:183:7)
    at Immediate.readNext [as _onImmediate] (/Users/para042/linkguardian/html2links/node_modules/line-reader/lib/line_reader.js:269:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[Safari Bookmarks.txt](https://github.com/CCharlieLi/bookmark-parser/files/1752569/Safari.Bookmarks.txt)

**Comment by alexisparis** [comment]
seems related to the fact that safari generate folder like :
&lt;DT&gt;&lt;H3 FOLDED&gt;Favorites&lt;/H3&gt;

with FOLDED attribute without value

**Comment by CCharlieLi** [comment]
Thanks @alexisparis , good catch. Maybe it's time to make it work on Safari bookmark, I'll do some investigations and any pull request is welcome.
