### ISSUE TITLE
node-gyp build fail

### ISSUE THREAD

**Issue by linonetwo** [CCharlieLi/Bookmark#2]
```
% npm i bookmark-parser

> node-expat@2.3.17 install /Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
../node-expat.cc:11:26: error: no template named 'Handle'
  static void Initialize(Handle<Object> target)
                         ^
../node-expat.cc:481:23: error: no template named 'Handle'
  void Emit(int argc, Handle<Value> argv[])
                      ^
../node-expat.cc:29:69: error: too few arguments to function call, single argument 'context' was not specified
    target->Set(Nan::New("Parser").ToLocalChecked(), t->GetFunction());
                                                     ~~~~~~~~~~~~~~ ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:5947:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../node-expat.cc:98:24: error: no matching member function for call to 'ToString'
        str = info[0]->ToString();
              ~~~~~~~~~^~~~~~~~
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:2528:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:2544:35: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                    Local<String> ToString(Isolate* isolate) const);
                                  ^
../node-expat.cc:103:38: error: no matching member function for call to 'ToObject'
        Local<Object> obj = info[0]->ToObject();
                            ~~~~~~~~~^~~~~~~~
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
../node-expat.cc:124:30: error: too few arguments to function call, single argument 'isolate' was not specified
    int len = str.Utf8Length();
              ~~~~~~~~~~~~~~ ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:2678:3: note: 'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
../node-expat.cc:130:26: error: cannot initialize a parameter of type 'v8::Isolate *' with an rvalue of type 'char *'
    assert(str.WriteUtf8(static_cast<char *>(buf), len) == len);
                         ^~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note: expanded from
      macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:2738:26: note: passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
../node-expat.cc:301:13: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
      attr->Set(Nan::New(atts1[0]).ToLocalChecked(), Nan::New(atts1[1]).ToLocalChecked());
            ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../node-expat.cc:304:5: error: use of undeclared identifier 'Handle'; did you mean 'handle'?
    Handle<Value> argv[3] = { Nan::New("startElement").ToLocalChecked(),
    ^~~~~~
    handle
../../nan/nan_object_wrap.h:41:32: note: 'handle' declared here
  inline v8::Local<v8::Object> handle() const {
                               ^
../node-expat.cc:304:5: error: call to non-static member function without an object argument
    Handle<Value> argv[3] = { Nan::New("startElement").ToLocalChecked(),
    ^~~~~~
../node-expat.cc:304:12: error: 'Value' does not refer to a value
    Handle<Value> argv[3] = { Nan::New("startElement").ToLocalChecked(),
           ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:2240:17: note: declared here
class V8_EXPORT Value : public Data {
                ^
../node-expat.cc:304:19: error: use of undeclared identifier 'argv'
    Handle<Value> argv[3] = { Nan::New("startElement").ToLocalChecked(),
                  ^
../node-expat.cc:307:21: error: use of undeclared identifier 'argv'
    parser->Emit(3, argv);
                    ^
../node-expat.cc:317:5: error: use of undeclared identifier 'Handle'; did you mean 'handle'?
    Handle<Value> argv[2] = { Nan::New("endElement").ToLocalChecked(), Nan::New(name).ToLocalChecked() };
    ^~~~~~
    handle
../../nan/nan_object_wrap.h:41:32: note: 'handle' declared here
  inline v8::Local<v8::Object> handle() const {
                               ^
../node-expat.cc:317:5: error: call to non-static member function without an object argument
    Handle<Value> argv[2] = { Nan::New("endElement").ToLocalChecked(), Nan::New(name).ToLocalChecked() };
    ^~~~~~
../node-expat.cc:317:12: error: 'Value' does not refer to a value
    Handle<Value> argv[2] = { Nan::New("endElement").ToLocalChecked(), Nan::New(name).ToLocalChecked() };
           ^
/Users/linonetwo/.node-gyp/12.1.0/include/node/v8.h:2240:17: note: declared here
class V8_EXPORT Value : public Data {
                ^
../node-expat.cc:317:19: error: use of undeclared identifier 'argv'
    Handle<Value> argv[2] = { Nan::New("endElement").ToLocalChecked(), Nan::New(name).ToLocalChecked() };
                  ^
../node-expat.cc:318:21: error: use of undeclared identifier 'argv'
    parser->Emit(2, argv);
                    ^
../node-expat.cc:327:5: error: use of undeclared identifier 'Handle'; did you mean 'handle'?
    Handle<Value> argv[1] = { Nan::New("startCdata").ToLocalChecked() };
    ^~~~~~
    handle
../../nan/nan_object_wrap.h:41:32: note: 'handle' declared here
  inline v8::Local<v8::Object> handle() const {
                               ^
../node-expat.cc:327:5: error: call to non-static member function without an object argument
    Handle<Value> argv[1] = { Nan::New("startCdata").ToLocalChecked() };
    ^~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/linonetwo/Desktop/repo/zazu-firefox-bookmarks/node_modules/node-expat
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN zazu-chrome-bookmarks@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/linonetwo/.npm/_logs/2019-05-12T12_17_57_016Z-debug.log
```

**Comment by linonetwo** [comment]
While latest lz4 works, please upgrade.

**Comment by CCharlieLi** [comment]
Thanks @linonetwo I just updated all dependencies and CI passed. release v0.1.6
Closing.
